# Generated by Django 3.2 on 2022-06-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('subscribed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Course Registrations',
            },
        ),
    ]
